# ---- base image ----
FROM python:3.11-slim AS base

WORKDIR /app
ENV PYTHONUNBUFFERED=1

# ---- install dependencies ----
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ---- copy app ----
# ---- copy app ----
COPY backend/app ./app
COPY backend/pytest.ini .

# ---- run server ----
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--timeout-keep-alive", "60"]

